version: '3.8'

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    env_file: .env
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception_network
    env_file:
      - .env
    restart: always

networks:
  inception_network:

volumes:
  mariadb_data:
  wordpress_data:

